### Class ###

### Pega todas as classes.
GET  http://localhost:3003/class

### Criar nova turma.
POST http://localhost:3003/class
Content-Type: application/json

{
    "name": "Jobs"
}

### Pega todas as turmas ativas.
GET http://localhost:3003/activeClasses

### Edita o módulo por id.
PUT http://localhost:3003/classes/10
Content-Type: application/json

{
    "module": 5
}



### Student ###

### Pega estudante por nome.
GET http://localhost:3003/student?name=l

### Edita a turma do estudante por id.
PUT http://localhost:3003/student/194
Content-Type: application/json

{
    "classId": 12
}

### Cria um estudante.
POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "userTest",
    "email": "userTest12@shaw.com",
    "birthDate": "10/10/1995",
    "hobby":["correr"]
}    
 


### Instructor ###

### Criar um novo instrutor.
POST http://localhost:3003/instructor
Content-Type: application/json

{
    "name": "Teste 4000", 
    "email": "2444a66asd6666@gmail.com", 
    "birthDate": "2005/12/12",
    "skills": ["OOP", "Typescript", "nonono"]
}

### Pegar todos os instrutores.
GET http://localhost:3003/instructors

### Mudar instrutor de turma.
PUT http://localhost:3003/instructor/2
Content-Type: application/json

{
    "classId": 4
}