### Class ###

### Pega todas as classes.
GET  https://labe-system-shaw3.herokuapp.com/class

### Criar nova turma.
POST https://labe-system-shaw3.herokuapp.com/class
Content-Type: application/json

{
    "name": "Malaquias"
}

### Pega todas as turmas ativas.
GET https://labe-system-shaw3.herokuapp.com/activeClasses

### Edita o módulo por id.
PUT https://labe-system-shaw3.herokuapp.com/classes/10
Content-Type: application/json

{
    "module": 0
}



### Student ###

### Pega estudante por nome.
GET https://labe-system-shaw3.herokuapp.com/student?name=la

### Edita a turma do estudante por id.
PUT https://labe-system-shaw3.herokuapp.com/student/194
Content-Type: application/json

{
    "classId": 5
}

### Cria um estudante.
POST https://labe-system-shaw3.herokuapp.com/student
Content-Type: application/json

{
    "name": "userTest",
    "email": "userTest120@shaw.com",
    "birthDate": "10/10/1091",
    "hobby":["correr"]
}    
 


### Instructor ###

### Criar um novo instrutor.
POST https://labe-system-shaw3.herokuapp.com/instructor
Content-Type: application/json

{
    "name": "Teste 4000", 
    "email": "test00101s@gmail.com", 
    "birthDate": "10/10/1990",
    "skills": ["OOP"]
}

### Pegar todos os instrutores.
GET https://labe-system-shaw3.herokuapp.com/instructors

### Mudar instrutor de turma.
PUT https://labe-system-shaw3.herokuapp.com/instructor/10
Content-Type: application/json

{
    "classId": 1
}