GET  http://localhost:3003/class

### 
POST http://localhost:3003/class
Content-Type: application/json

{
    "name": "Jobs"
}

###
GET http://localhost:3003/activeClasses

### 
PUT http://localhost:3003/classes/4
Content-Type: application/json

{
    "module": 5
}




###
GET http://localhost:3003/student?name=l

###
PUT http://localhost:3003/student/1
Content-Type: application/json

{
    "classId":10
}

###
POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "userTest",
    "email": "userTest@shaw.com",
    "birthDate": "1",
    "hobby":["correr"]
}